spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payproject
    username: postgres
    password: 8834
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: false
